### ISSUE TITLE
Documentation clarification (Webhook)

### ISSUE THREAD

**Issue by stalsma** [thiagobruch/amazon_shopping_list_scrape#10]
I pulled and configured the latest image, and its working fine.  Nice work.  The use of screenshots is particularly useful in debugging.  Just have to expose 8888 and know what it is actually being shown. 

I ran into minor configuration issues, both specific to my use case, but worth mentioning the documentation.

1. Webhook url: this must the an address internal to the network.  I usually access my HA over a cloudflared tunnel, which has a public IP.  But the default configuration of HA causes those calls to fail.
2. The sample code that adds items to the list first checks to see if it is already on the list.  But considers completed items to be on the list.  I'm using the Bring integration, which marks items as complete, instead of deleting them.  So after purchasing milk last week, it will be marked as complete.  Adding milk to the list via Alexa will trigger the webhook, but b/c it status is *complete*, it never makes it past the if condition.  So for some users, the status filter may need to omit completed items:
```
action:
  - action: todo.get_items
    data:
      status:
        - needs_action
    response_variable: todo
    ....
```

3.  Also worth mentioning is that the `entity_id` in the webhook needs to be changed in 2 places to match whatever is configured in HA.  In the case using the Bring integration, it will match the Bring list name; it will not (necessarily) use the default id of `todo.shopping_list`.

**Comment by thiagobruch** [comment]
hi @stalsma 

Sorry for the late reply, I saw the email notification and due to work stuff, I forgot to check it here again.
Regarding your points:
1 - That is a "limitation" on the HA side.
2 - Adding that to the documentation
3 - Adding that to the documentation
