### ISSUE TITLE
Documentation of env config options

### ISSUE THREAD

**Issue by stalsma** [thiagobruch/amazon_shopping_list_scrape#4]
Consider adding to documentation the additional env settings that can be used in the docker version:

* HA_WEBHOOK_URL
* Amazon_Sign_in_URL
* Amazon_Shopping_List_Page

Also note that `HA_WEBHOOK_URL` should be set to the internal network address as seen w/in the home network.  HA doesn't permit access to webhooks from outside the local network in the default configuration.  I originally had this set to my cloudflared tunnel public address, and it was failing silently.

**Comment by thiagobruch** [comment]
Fixed the README.MD

**Comment by thiagobruch** [comment]
Fixed the README.MD
