### ISSUE TITLE
Add log-level env variable

### ISSUE THREAD

**Issue by stalsma** [thiagobruch/amazon_shopping_list_scrape#6]
The commented out console.log are very helpful to knowing whether the app is running and succeeding.  I found myself spinning up a new container, and then uncommenting the same lines every time as I was debugging.  

Consider refining to error/info/debug and letting user set those from env var along with time logged.  That way when running from docker, it's simply a matter of looking at the debug log as it scrolls by.

It would quickly help answer the question "is this thing on" for new users.

**Comment by thiagobruch** [comment]
Added variable to show the debug log
