### ISSUE TITLE
Could you make it also run on arm v8 docker?

### ISSUE THREAD

**Issue by michaelhenningersrb** [thiagobruch/amazon_shopping_list_scrape#7]
I am running my docker instance on my raspberry pi 4 32 Bit ( don't ask why ;) )

Is there a change to get it running on 32 bit docker?

` ! amazon-scraper The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested `

**Comment by thiagobruch** [comment]
Hi @michaelhenningersrb ,

To be honest, I don't know if it will be possible.
The container uses Chromium, nodejs (with puppeteer otpauth dotenv) and I'm not sure we have a 32bit version for these.
