### ISSUE TITLE
Two-way sync?

### ISSUE THREAD

**Issue by alexiri** [thiagobruch/amazon_shopping_list_scrape#8]
Thanks a lot for this project! Are there any plans to implement two-way sync in the future?

**Comment by thiagobruch** [comment]
Hi @alexiri ,

Unfortunately, no plans for a 2 way sync.
The way we are currently doing is scrapping the Amazon Shopping List page (reading from the page).
It would be far more difficult (at least for me) to write something back.

Maybe someone could take this project and improve to add the 2 way sync.

**Comment by SavageCore** [comment]
Shameless plug! 

https://github.com/SavageCore/HA_Addons/tree/main/alexa_shopping_list_sync

**Comment by thiagobruch** [comment]
> Shameless plug!
> 
> https://github.com/SavageCore/HA_Addons/tree/main/alexa_shopping_list_sync

Wow, that's nice.
I will try on my end.

Thanks for sharing :) :)

**Comment by thiagobruch** [comment]
For a two way sync, please using @SavageCore 's project from:
https://github.com/SavageCore/HA_Addons/tree/main/alexa_shopping_list_sync
