### ISSUE TITLE
too many OTPs

### ISSUE THREAD

**Issue by markrennie71** [thiagobruch/amazon_shopping_list_scrape#9]
Hello

I'm loving this thanks but it is affecting other amazon integrations due to the following
There was a problem
You have requested too many OTPs today. Please try again later.

Is there anyway to limit these please?

Cheers

**Comment by thiagobruch** [comment]
Hi @markrennie71 ,

Unfortunately, every time the program runs, it has to authenticate.
I'm not aware of the problem with too many OTP requests.

However, a simple solution would be to change the frequency of the pooling interval.
You can change to every hour for example:
-e polling_interval='3600'

**Comment by markrennie71** [comment]
Fair enough. Will change to every hour and see if it can be stopped over night.
